version: "3"
name: springboot-mysql-compose

services:
  app:
    container_name: huyqn-springboot
    build:
      context: .
      dockerfile: ./Dockerfile2
    image: huyqn/springboot
    ports:
      - "8082:8080"
    # restart: on-failure
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - java-app

  mysql:
    container_name: huyqn-java-mysql
    image: "mysql:8.0"
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: mydb
      MYSQL_USER: huyqn
      MYSQL_PASSWORD: qnhuy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3306"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    volumes:
      - khalid-java-mysql-data:/var/lib/mysql
    networks:
      - java-app

volumes:
  khalid-java-mysql-data:
networks:
  java-app:
    name: java-app
